version: '3'

services:

  redis:
    image: redis
    container_name: redis
    ports: [ "6379:6379" ]

  postgres:
    image: postgres
    container_name: postgres
    ports: [ "5432:5432" ]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    ports: [ "4040:4040" ]
    command: ngrok http app:8080

  localstack:
    container_name: localstack
    image: localstack/localstack
    environment:
      - DEFAULT_REGION=us-west-1
      - SERVICES=sqs
      - DEBUG=1 # Uncomment to debug SQS
    ports:
      - "4566:4566"
    volumes:
      - ./.localstack:/docker-entrypoint-initaws.d

  app:
    depends_on:
      - redis
      - postgres
      - localstack
    volumes:
      - .:/app
    build:
      context: .
    ports:
      - "8080:8080" # main port
      - "9229:9229" # main debug port
      - "8081:8081" # worker port
      - "9230:9230" # worker debug port
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/jira-dev
      REDISX_CACHE_HOST: redis
