version: 2.1

jobs:
  build:
    docker:
      - image: 861281107445.dkr.ecr.us-west-1.amazonaws.com/circle-docker-base:latest
        aws_auth:
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Mya Common CICD
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              TARGET="--target=dev-multi"
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              TARGET="--target=stage-multi"
            elif [ "${CIRCLE_BRANCH}" == "deploy" ]; then
              TARGET="--target=prod-multi"
            else
              TARGET="--no-deploy"
            fi
            ./make.sh ${TARGET}
