blank_issues_enabled: false
contact_links:
  - name: Github for Jira Documentation
    url: https://support.atlassian.com/jira-cloud-administration/docs/integrate-with-github/
    about: Learn more about how to install, configure and use GitHub for Jira
  - name: Support Requests and Bug Reports
    url: https://support.atlassian.com/contact/#/
    about: Need some help? Please submit a support request or bug report via Jira Software Support portal
  - name: Feature Requests and Product Suggestions
    url: https://jira.atlassian.com/secure/Dashboard.jspa
    about: Suggest an idea or solution for the Github for Jira app. When creating tickets, please select the project-"Jira Software Cloud" and the component-"Integration - GitHub - Marketplace".
